sudo: false

language: go

go:
  - 1.11.x

git:
  depth: 1

services:
  - docker

before_script:
  - make deps

script:
  - make test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_REGION"
  app: "hunt-dex"
  env: "hunt-dex-dev"
  bucket_name: "elasticbeanstalk-us-west-2-264136589261"
  on:
    branch: master
